## SPACES! not tabs
## Also, pascal case
Guide: |     
    Quick Guidelines for YAML
  
    !!str: A string value (the default if no type is specified).
    !!bool: A boolean value (true or false).
    !!int: An integer value.
    !!float: A floating-point value.
    !!null: A null value (equivalent to None in Python).
    !!timestamp: A date/time value.
    !!binary: A binary data value.

Rationale: |
  Signature Evasion:
    This section is meant to avoid being picked up by the same message being sent over and over again (i.e. 100 inbound Sleep commands will look different each time) 

    Padding: Adds random characters of a random length to feilds that are not used (or to the dedicated padding feilds), thus altering
              the message signature/hash/whatevr

## == Signature Evasion == ##
Padding:
  ## Technical: This pool consists of characters available for padding, from which a random selection will be made from
  ## English:   The set of characters that can be used when creating the random padding
  Characters  : !!str "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  ## Minimum length of padding string
  MinLength   : !!int 1
  ## Max length of padding string
  MaxLength   : !!int 25


