## !!pascal case!!
Guide: |     
    Quick Guidelines for YAML

    !!str: A string value (the default if no type is specified).
    !!bool: A boolean value (true or false).
    !!int: An integer value.
    !!float: A floating-point value.
    !!null: A null value (equivalent to None in Python).
    !!timestamp: A date/time value.
    !!binary: A binary data value.

## == EndPoints == ##
## Mappings of all the endpoints for the rest server. Define whatever you'd like, and the URL will match the endpoint
## Ex: Server.Base will go to http://IP/server
## Ex: Misc.Login: http://IP/login
## Ex: Server.SpawnTcplistener: http://IP/server/spawntcplistener"
## Ex: If you change Misc.Login (http://IP/login) to "hacker/portal", you can access it at http://IP/hacker/portal

## These are CASE SENSITIVE!

Server:
  # Base url, ex: http://IP/server
  Base: "server"
  SpawnTcpListener: "server/spawntcplistener"

Agent:
  Base: "agent"

FileServer:
  # Base url, ex: http://IP/files
  Base: "files"
  # Where uploaded files are stored
  Uploads: "ApiEngine/files"

Misc:
  ## This should stay the same, unless you communicate the location of the "login" to other parties. 
  ## Otherwise, the Schema may not be accessible
  ## I'm not stopping you from changing it (do what you want lol), just warning
  Login: "login"
  Schema: "schema"

Home:
  # Base url, ex: http://IP/home
  Base: "home"

## == HTML Pages == ##
## Each one of these are a lsit of potential HTML pages to display.
## Each one will be randomly sellected for which will be displayed. 
## Change it to only one item in the list for a consistent page


## A path to potential homepages for the API server. These will be randomly selected on which to load
HomepageList: 
  - "ApiEngine/html/homepage-MLP.html" # I Promise I'm not a brony... Just wanted something colorful 
  - "ApiEngine/html/homepage-Default.html"

## Messages to display in a 404 not found. Note, that all 404's return a 200
## this is to prevent (or slow...) URL scraping/discovery
NotFoundList_404:
  - "ApiEngine/html/errorcodes/404-default.html"
  - "ApiEngine/html/errorcodes/404-default-alt.html"
