---
plugin:
  name: http_listener_01
  type: simplec2_http_listener
  version: 1.0.0
  description: simple c2 http listener
  author: ryanq.47
  license: _
  subroutine:
    ## How often the subroutine is triggered
    interval: 5
    ## Symbol to print for subroutine based events
    symbol: "[subr]"
  
  ## Listener stuff
  network:
    ip: "0.0.0.0"
    port: 5001
    option3: 42

  logging:
    level: "DEBUG" ## DEBUG, INFO, WARN

server:
  ip: "127.0.0.1"
  port: 5000
  option3: 42
  # Add more configuration options as needed
