## SPACES! not tabs

general:

  ## Themes are in beta, may not work as expected!
  #Ex: theme: "mytheme.css"
  theme: "Default"

startup:
  show-project-picker: True


osint:
  reddit:
    key:
    username:
    password:
