## SPACES! not tabs

Guide: |     
    Quick Guidelines for YAML
  
    !!str: A string value (the default if no type is specified).
    !!bool: A boolean value (true or false).
    !!int: An integer value.
    !!float: A floating-point value.
    !!null: A null value (equivalent to None in Python).
    !!timestamp: A date/time value.
    !!binary: A binary data value.


general:

  ## Themes are in beta, may not work as expected!
  #Ex: theme: "mytheme.css"
  theme: "Default"

startup:
  show-project-picker: True

sql_table_view:
  ## The widest the columns DEFAULT to. Can still manually expand to any size
  max_column_width: !!int 100 
  ## 5-10 Reccomended
  max_row_height: !!int 5


osint:
  reddit:
    ## These are burner creds (link to a real, useless account)
    secret_token: "nZbrbXJUJ8xgcITMCroDfg4YOB2pIA"
    client_id: "GAlh4V1Wvo3h_lg2H9v4ZQ"
    username: "Level_Statement8564"
    password: "s7zmf4@LJP*5C#^Nim3HU5ZtF&cpV9"

