## SPACES! not tabs
## Also, pascal case
Guide: |     
    Quick Guidelines for YAML
  
    !!str: A string value (the default if no type is specified).
    !!bool: A boolean value (true or false).
    !!int: An integer value.
    !!float: A floating-point value.
    !!null: A null value (equivalent to None in Python).
    !!timestamp: A date/time value.
    !!binary: A binary data value.


System:
  Themes: 
    ## Currenth themes: "default", "dark", "light", "system"
    ## dark: https://github.com/5yutan5/PyQtDarkTheme
    Theme: !!str "dark"
    ## hex color code
    Accent: !!str "#7DF9FF"
    Font: !!str "Roboto"
    FontSize: !!int 11

  Startup:
    ShowProjectPicker: !!bool False

  Logging:
    #Not Working
    LogsToStdout: !!bool True
    ## in kb, zips up logs and starts a new file. otherwise some things may get bogged down
    LogRoleSize: 1000


Sql:
  ## settings for the tables displayed in the program
  SqlTableView:
    ## The widest the columns DEFAULT to. Can still manually expand to any size
    MaxColumnWidth: !!int 100 
    ## 5-10 Reccomended
    MaxRowHeight: !!int 5

    SqlRightclickMenu:
      ## THe search url for the browser you want, no http/s
      ## Google: google.com/search?q=
      DefaultBrowserUrl: !!str "duckduckgo.com/?q="

## modules n stuff
Osint:
  Reddit:
    ## These are burner creds (link to a real, useless account)
    SecretToken: "nZbrbXJUJ8xgcITMCroDfg4YOB2pIA"
    ClientId: "GAlh4V1Wvo3h_lg2H9v4ZQ"
    Username: "Level_Statement8564"
    Password: "s7zmf4@LJP*5C#^Nim3HU5ZtF&cpV9"

C2:
  Local:
    ## Milliseconds
    ServerRefreshLog: !!int 10000 
    ## Kills the server when you close the GUI, False = leave it running
    KillServerOnExit: True
