name: Python (logec) Compile & Publish via Nuitka

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nuitka
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --requirement requirements.txt
      - name: Get latest tag name
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
      - name: Create release and upload compiled code
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          release_name: Ubuntu Release ${{ steps.latest_tag.outputs.tag }}
          body: |
            Logec-Suite Compiled
          draft: false
          prerelease: false
      - name: Upload compiled code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # location of files
          asset_path: ./logec-suite
          # what to name the zip file
          asset_name: logec-suite.zip
          asset_content_type: application/zip
