name: Python (logec) Compile & Publish via Nuitka

on: 
  [workflow_dispatch]
 
jobs:
  build:
    runs-on: ubuntu-20.04	
    # Expirement with older version for sanity check

    steps:
      - uses: actions/checkout@v2
      - name: Install Nuitka
        run: |
          python3 --version
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --requirement requirements.txt
          
      - name: Compile Python code with Nuitka
        run: |
          make compile 

 
      - name: Set environment variable for current date
        run: echo "RELEASE_NAME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: dirs
        run: |
          tree
      
      - name: Create release and upload compiled code
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: version-${{ env.RELEASE_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Logec-Suite Compiled
          draft: false
          prerelease: false
        ## need to figure out folder structure b4 upload

      - name: Zip compiled code
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: ./compiled-logec-suite.zip
      - name: Post Zip Dirs
        run: |
          tree
      - name: Upload compiled code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # location of files
          asset_path: ./compiled-logec-suite.zip
          # what to name the zip file
          #asset_name: logec-suite-ubuntu-${{ env.RELEASE_NAME }}
          asset_name: compiled-logec-suite.zip
          asset_content_type: application/zip
